### ISSUE TITLE
java.lang.ClassNotFoundException: cpw.mods.fml.common.launcher.FMLTweaker

### ISSUE THREAD

**Issue by WolfieWaffle** [MinecraftForge/FML#515]
Sorry, I'm new to Github, so i'm not sure how it works, but I was using Minecraft forge and I got this:

Sep 14, 2014 1:07:31 PM net.minecraft.launchwrapper.LogWrapper log
INFO: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
Sep 14, 2014 1:07:32 PM net.minecraft.launchwrapper.LogWrapper log
SEVERE: Unable to launch
java.lang.ClassNotFoundException: cpw.mods.fml.common.launcher.FMLTweaker
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:102)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:94)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

Does anyone know what to do?

**Comment by Swandar** [comment]
WolfieWaffle could you tell me how you fixed it?

**Comment by AndroidDoctorr** [comment]
How did you fix it?

**Comment by liach** [comment]
Probably you need to install forge properly and use a good, not cracked, launcher.

**Comment by MCOfficer** [comment]
i'm having the same error.
```
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
[14:56:25] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[14:56:25] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraftforge.fml.common.launcher.FMLTweaker
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_121]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

```
this happens with several 1.10.2 forge versions (not 1.7.10 though), no matter if online or not. launcher is not cracked, everything was fine and has worked at least once.

i use oracle java 1.8.0_121 on linux mint 18, 64bit (ubuntu 16.04 based).
edit: i also tried it with the java executable unchecked. not sure if the linux version of minecraft comes with a bundled java, if yes it doesn't work either.
edit 2: interesting, the exact same setup that crashes in the minecraft launcher works in the multimc launcher. i'll stick with this, so at least my problem has been fixed.
