### ISSUE TITLE
minecraft forge promblem

### ISSUE THREAD

**Issue by UnvoicedTiger6** [MinecraftForge/FML#674]
[18:22:38] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[18:22:38] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: cpw.mods.fml.common.launcher.FMLTweaker
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[?:1.8.0_25]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_25]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_25]
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
    at java.lang.Class.forName0(Native Method) ~[?:1.8.0_25]
    at java.lang.Class.forName(Class.java:344) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

what dose this meen

**Comment by liach** [comment]
> (Archive Only: Merged into Forge proper)

And put this on http://www.minecraftforge.net/
